#!/usr/bin/python

import socket

host    = 'localhost'
port    = 50000
backlog = 1
size    = 16

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind((host,port))
sock.listen(backlog)

while True:
    connection, client_address = sock.accept()
    try:
        while True:
            data = connection.recv(size)
            if data:
                connection.sendall(data)
            else:
                break
    finally:
        connection.close()
