#!/bin/bash

test_name="$@"
test_name="$(echo $test_name | tr '[:upper:]' '[:lower:]' | tr ' ' '_')"
test_path="$test_name/$test_name.lua"

mkdir -p $test_name
echo '#!/usr/bin/env lua' > $test_path
chmod +x $test_path
