#!/bin/bash

cpu_nb="$1"
[ "$cpu_nb" = "" ] && cpu_nb=4

(
# compilation
sleep 10
for ((i=0;i<cpu_nb;i++)); do
  echo "compilation run_cpu $i"
  ./run_cpu compilation $i > /dev/null
done
# run
for ((i=0;i<cpu_nb;i++)); do
  ./run_cpu run $i &
done
)&

./run_top $cpu_nb
