#!/bin/bash

usage() {
  echo "usage: $0 <address>"
  exit 1
}

add="$1"
[ "$((add))" -eq "$((add))" ] &> /dev/null || usage

ip="$(grep "ip" server.txt | awk '{print $2}')"
port="$(grep "port" server.txt | awk '{print $2}')"

./client -a $ip -p $port -r $add
