#!/usr/bin/python3

import socket

host    = 'localhost'
port    = 50000
size    = 16

sock    = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((host,port))

try:
    message = input("Enter message: ")
    sock.sendall(message.encode())
    # Look for the response
    amount_received = 0
    amount_expected = len(message)
    while amount_received < amount_expected:
        data = sock.recv(size)
        if data:
            amount_received += len(data)
        print(data.decode())
finally:
    sock.close()
