#!/bin/bash

set -e

mkdir -p output
cp -rf src/*/* output
cd output

verilator --binary -j 0 top.sv dpi.cpp server.cpp
cat << EOF

----------------------------------------
-- simulation start
----------------------------------------
EOF
./obj_dir/Vtop
