#!/bin/bash

set -e

mkdir -p output
cp -rf src/* output
cd output

verilator --binary -j 0 -Wall top.sv
cat << EOF

----------------------------------------
-- simulation start
----------------------------------------
EOF
./obj_dir/Vtop
